[package]
name = "sydf"
version = "0.1.0"
authors = ["Filip Parag <filip@parag.rs>"]
edition = "2018"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
toml = "0.5.7"

[profile.release]
opt-level = 3