[package]
name = "sydf"
version = "0.1.0"
authors = ["Filip Parag <filip@parag.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
