#! /bin/env bash

SYDFCONFIG=$HOME/.config/sydf.conf
SYDFDIR=""
if [ -f $SYDFCONFIG ]; then
	SYDFDIR=`cat $SYDFCONFIG`
else
	echo "sydf needs to be initialized"
fi

function path {

	P=""
	if [ -z $1 ] || [ $1 = "." ]; then
		P=$PWD
	elif [ ${1:0:1} = "/" ]; then
		P=$1
	else
		P=$PWD/$1
	fi

	echo $P

}

function init {
	
	DIR=`path $1`;	

	if [ -e $SYDFCONFIG ]; then
		if [ $DIR = `cat $SYDFCONFIG` ]; then
			echo "sydf is already configured to use this directory"
		else
			echo "sydf is configured to use another directory"
			echo "run 'sydf reinit' to reinitialize"
		fi
	else
		echo $DIR > $SYDFCONFIG
	fi

}

